### ISSUE TITLE
Make better sample description plots

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/us_climate_emotions_map#25]
From the feedback meeting on May 24th:

- Horizontal bar chart(s) combining different variables (coloured differently)
  - All demographic variables aside from impact & q2 in one histogram, but put age/sex/race/ethnicity first
  - Add asterisk to highlight that some of the responses (age/sex/race/ethnicity) are weighted
- Then impacts and q2 as different plots
  - q2 also horizontal
- Colors scheme for these subplots
- For impact: only keep the "yes" bars
- Show both percentage and counts directly on the plot (no hover tooltip)
  - Show percentage on the axis (if possible/not too challenging, maybe have a function param to select whether percentages/counts should be along the axis? in case Eric changes his mind)
- Reduce default margins of plotly figure to minimize unnecessary whitespace
  - e.g., something like `fig.update_layout("margin": {"l": 30, "r": 30, "t": 30, "b": 30})` appears to work well

See @koudyk's whiteboard drawing in meeting minutes

**Comment by alyssadai** [comment]
Thanks @michellewang for creating this issue! 🎉 I updated it slightly based on what I remember of Eric's preferences.

Also, I can separately add a text element in the drawer that holds these descriptive plots with the text for the asterisk, so no worries about having a legend for that.

**Comment by alyssadai** [comment]
ah, added one more point on reducing margins! :)
