### ISSUE TITLE
Investigate serializing all plots before/at startup to speed up app

### ISSUE THREAD

**Issue by alyssadai** [neurodatascience/us_climate_emotions_map#87]
Per question (`subquestion="all"`), we need 6 variations of graphs:

1. Per state, we need 2 plots:
    1. one with `threshold=None` (showing all endorsement/response levels)
    2. one with `threshold=DEFAULT_QUESTION["outcome"]` (thresholding responses at "3+")
 1. For national-level responses (`state=None`), we need 4 plots:
    1. one with `threshold=None` (showing all endorsement/response levels)
    2. one with `threshold=DEFAULT_QUESTION["outcome"]` (thresholding responses at "3+")
    3. one with `threshold=None` **AND** `stratify=True` (stratify bar graph by party affiliation)
    4. one with `threshold=DEFAULT_QUESTION["outcome"]` **AND** `stratify=True`

List of states can be obtained from one of the following:
- `state` column of `DATA_DICTIONARIES["state_abbreviations.tsv"]`
- `state` column of `SURVEY_DATA["samplesizes_state.tsv"]`

List of questions can be obtained from:
- `question` column of `DATA_DICTIONARIES["question_dictionary.tsv"]`

### Where should the figures live?
Maybe under code/assets/, and the script can live in code/?

**Comment by alyssadai** [comment]
Hey @surchs, thanks for helping to tackle this issue!

I've updated the iss description with more details of the total variants of graphs needed, and where you can find the necessary question/state info. Let me know if I missed anything!

**Comment by surchs** [comment]
So the good news is: serialization works nicely. 
The bad news is: loading the serialized object into memory takes around 45 seconds. We'll have to see how often the dashboard will actually do that.
